add function to get disclaimer and add it to the created downloaded zip
Innovate-Inc/sweri-data-tools pull request #2
Opened 2024-10-24 17:28 UTC by rdmccann

2024-10-29 19:19 UTC, tbock requested changes
@rdmccann @krewritten this feedback was for both of you as I know Robert didn't start this.   @rdmccann can you refactor based on my feedback please.

2024-10-29 19:39 UTC, krewritten commented on sweri_utils/files.py
> +            outfile = create_zip(tmp_path, out_dir, out_name)
@tbock that makes sense to me, probably should've separated that out earlier on.

2024-11-04 16:28 UTC, krewritten approved these changes

2024-11-04 17:01 UTC, tbock approved these changes

2024-11-04 17:17 UTC, merged